### ISSUE TITLE
i am running my application service in http://api:8000 using docker-compose. how can i communicate the backend with the frontend?

### ISSUE THREAD

**Issue by Raisul1234** [fastapi-admin/fastapi-admin#36]

**Comment by long2ice** [comment]
You need expose backend port to host

**Comment by Raisul1234** [comment]
> You need expose backend port to host

can you please share the nginx configuration file and live docker-compose file for production bro..?
also in rest admin what will be my publicpath.

**Comment by Raisul1234** [comment]
> > You need expose backend port to host
> 
> can you please share the nginx configuration file and live docker-compose file for production bro..?
> also in rest admin what will be my publicpath.

const API_URI = process.env.VUE_APP_API_URL || 'http://127.0.0.1:8000/admin/'
in this part i am using http://api:8000/admin but while serving through nginx i am getting blocked by browser due to mixed content. 
As everything is served using https but APi_uri is being served by http . So, i am stucked on this since last week and could not find a legit solution. Can you please help?

**Comment by long2ice** [comment]
Just use nginx reverse proxy your api server:
```
server {
    listen 443 ssl http2;
    server_name fastapi-admin-api.long2ice.cn;
    ssl_certificate /etc/nginx/ssl/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/*.long2ice.cn.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    location /{
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

**Comment by Raisul1234** [comment]
how are you serving the dist file?

**Comment by long2ice** [comment]
Use nginx also

**Comment by Raisul1234** [comment]
@long2ice show me that config file please.

**Comment by long2ice** [comment]
Why not use google? That just simple.

**Comment by Raisul1234** [comment]
> Why not use google? That just simple.
 i am basically using this configuration .but getting error.. that's why i was asking for help .. 
 ```
upstream api {
    server                     api:8000;
  }

server {
    listen                            80;
    return 301 https://$host$request_uri;
  }



server {
    server_name      chatbot.nblbd.com;
    access_log                     off;
    listen 443                     ssl;

    # ssl on;
    ssl_certificate          /etc/ssl/certs/nblbd.crt;
    ssl_certificate_key      /etc/ssl/certs/nblbd.key;
    
    root /vue/dist;
    index index.html;

    location /admin {
        try_files $uri /index.html;
    }

   location / {
        proxy_connect_timeout       300;
        proxy_send_timeout          300;
        proxy_read_timeout          300;
        send_timeout                300;
        proxy_pass                  http://api;
        proxy_set_header            X-Forwarded-Host $server_name;
        proxy_set_header            X-Real-IP $remote_addr;
        proxy_cache_valid           200 404  1m;
        proxy_cache_valid           302 20m;
        proxy_cache_use_stale       error timeout invalid_header updating;
        proxy_redirect              off;
    }

}
```

**Comment by long2ice** [comment]
```
upstream api {
   server                     api:8000;
 }

server {
   listen                            80;
   return 301 https://$host$request_uri;
 }



server {
   server_name      chatbot.nblbd.com;
   access_log                     off;
   listen 443                     ssl;

   # ssl on;
   ssl_certificate          /etc/ssl/certs/nblbd.crt;
   ssl_certificate_key      /etc/ssl/certs/nblbd.key;

   location /{
       root /vue/dist;
       index index.html;
   }

  location /admin {
       proxy_connect_timeout       300;
       proxy_send_timeout          300;
       proxy_read_timeout          300;
       send_timeout                300;
       proxy_pass                  http://api;
       proxy_set_header            X-Forwarded-Host $server_name;
       proxy_set_header            X-Real-IP $remote_addr;
       proxy_cache_valid           200 404  1m;
       proxy_cache_valid           302 20m;
       proxy_cache_use_stale       error timeout invalid_header updating;
       proxy_redirect              off;
   }

}
```

I don't know whether it can run, you can try yourself.

**Comment by Raisul1234** [comment]
`upstream api {
   server                     api:8000;
 }

server {
   listen                            80;
   return 301 https://$host$request_uri;
 }

server {
   server_name      chatbot.nblbd.com, localhost;
   access_log                     off;
   listen 80                     ;

   # ssl on;

   root /vue/dist;
   index index.html;

   location /admin{

       try_files $uri /index.html;
   }

  location /nbl {
       proxy_connect_timeout       300;
       proxy_send_timeout          300;
       proxy_read_timeout          300;
       send_timeout                300;
       proxy_pass                  http://api;
       proxy_set_header            X-Forwarded-Host $server_name;
       proxy_set_header            X-Real-IP $remote_addr;
       proxy_cache_valid           200 404  1m;
       proxy_cache_valid           302 20m;
       proxy_cache_use_stale       error timeout invalid_header updating;
       proxy_redirect              off;
   }

}`
this one is my staging configuration for nginx that works fine i can easily serve the dist file through this using 
VUE_APP_API_URL=http://localhost:8000/admin/

but while serving for production 
`upstream api {
   server                     api:8000;
 }

server {
   listen                            80;
   return 301 https://$host$request_uri;
 }



server {
   server_name      chatbot.nblbd.com;
   access_log                     off;
   listen 443                     ssl;

   # ssl on;
   ssl_certificate          /etc/ssl/certs/nblbd.crt;
   ssl_certificate_key      /etc/ssl/certs/nblbd.key;
   root /vue/dist;
   index index.html;
   location /admin{

       try_files $uri /index.html;
   }

  location /nbl {
       proxy_connect_timeout       300;
       proxy_send_timeout          300;
       proxy_read_timeout          300;
       send_timeout                300;
       proxy_pass                  http://api;
       proxy_set_header            X-Forwarded-Host $server_name;
       proxy_set_header            X-Real-IP $remote_addr;
       proxy_cache_valid           200 404  1m;
       proxy_cache_valid           302 20m;
       proxy_cache_use_stale       error timeout invalid_header updating;
       proxy_redirect              off;
   }

}`
this settings does not give me expected output.. in the  dist build  i am using 
VUE_APP_API_URL=https://chatbot.nblbd.com/admin/ 
i am showing you the the images below,
![Uploading Screenshot 2021-03-20 at 12.12.40  @AM.png…]()
<img width="1440" alt="Screenshot 2021-03-20 at 12 13 01 AM" src="https://user-images.githubusercontent.com/76686890/111825000-23065900-8911-11eb-9ab7-92282fce66f2.png">

 what i am getting.. i am almost there bro. what i am doing wrong?

**Comment by Raisul1234** [comment]
> ```
> upstream api {
>    server                     api:8000;
>  }
> 
> server {
>    listen                            80;
>    return 301 https://$host$request_uri;
>  }
> 
> 
> 
> server {
>    server_name      chatbot.nblbd.com;
>    access_log                     off;
>    listen 443                     ssl;
> 
>    # ssl on;
>    ssl_certificate          /etc/ssl/certs/nblbd.crt;
>    ssl_certificate_key      /etc/ssl/certs/nblbd.key;
> 
>    location /{
>        root /vue/dist;
>        index index.html;
>    }
> 
>   location /admin {
>        proxy_connect_timeout       300;
>        proxy_send_timeout          300;
>        proxy_read_timeout          300;
>        send_timeout                300;
>        proxy_pass                  http://api/admin;
>        proxy_set_header            X-Forwarded-Host $server_name;
>        proxy_set_header            X-Real-IP $remote_addr;
>        proxy_cache_valid           200 404  1m;
>        proxy_cache_valid           302 20m;
>        proxy_cache_use_stale       error timeout invalid_header updating;
>        proxy_redirect              off;
>    }
> 
> }
> ```
> 
> I don't know whether it can run, you can try yourself.

**Comment by Raisul1234** [comment]
![Uploading Screenshot 2021-03-20 at 12.12.40 AM.png…]()

**Comment by Raisul1234** [comment]
<img width="1440" alt="Screenshot 2021-03-20 at 12 13 01 AM" src="https://user-images.githubusercontent.com/76686890/111825360-95773900-8911-11eb-9fc5-865c2e4425ec.png">

**Comment by Raisul1234** [comment]
![Uploading Screenshot 2021-03-20 at 12.12.40 AM.png…]()

**Comment by Raisul1234** [comment]
<img width="1440" alt="Screenshot 2021-03-20 at 12 12 40 AM" src="https://user-images.githubusercontent.com/76686890/111825650-e8e98700-8911-11eb-99b4-fcdb2debbc9d.png">

**Comment by Raisul1234** [comment]
@long2ice?

**Comment by Raisul1234** [comment]
/admin/site api is not giving a json response  in production. But locally i am getting it.
local respose: `

  |  
-- | --
name | "NBL-Admin"
login_footer | "NBL ADMIN - Dashboard"
login_description | "NBL Admin Dashboard"
locale | "en-US"
menus |  
0 |  
name | "Content"
children |  
0 |  
name | "UserModel"
url | "/rest/UserModel"
search_fields |  
0 | "platform_type"
1 |  
name | "TransactionModel"
url | "/rest/TransactionModel"
search_fields |  
0 | "transaction_type"
1 | "account_name"
2 |  
name | "TransactionAndBlacklistCountModel"
url | "/rest/TransactionAndBlacklistCountModel"
search_fields |  
0 | "platform_type"
1 | "account_no"
1 |  
name | "Auth"
children |  
0 |  
name | "User"
url | "/rest/User"
search_fields |  
0 | "username"
1 |  
name | "Role"
url | "/rest/Role"
2 |  
name | "Permission"
url | "/rest/Permission"
3 |  
name | "AdminLog"
url | "/rest/AdminLog"
search_fields |  
0 | "action"
1 | "admin"
2 | "model"
4 |  
name | "Logout"
url | "/logout"

`
production response :
"some html code in string " :( @long2ice any help?

**Comment by long2ice** [comment]
What's the detail? Can you access api directly？

**Comment by Raisul1234** [comment]
`Uncaught (in promise) TypeError: can't assign to property "fetched" on "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><meta name=\"renderer\" content=\"webkit\"><title>NBL Admin Dashboard</title><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.3.1/cosmo/bootstrap.min.css\"><link rel=\"stylesheet\" id=\"css-skin\"><link href=\"/admin/css/app.1f6b6a78.css\" rel=\"preload\" as=\"style\"><link href=\"/admin/css/chunk-vendors.a037d485.css\" rel=\"preload\" as=\"style\"><link href=\"/admin/js/app.67f73e35.js\" rel=\"preload\" as=\"script\"><link href=\"/admin/js/chunk-vendors.6bc95897.js\" rel=\"preload\" as=\"script\"><link href=\"/admin/css/chunk-vendors.a037d485.css\" rel=\"stylesheet\"><link href=\"/admin/css/app.1f6b6a78.css\" rel=\"stylesheet\"></head><body class=\"app sidebar-fixed\"><div id=\"css-custom\"></div><div id=\"app\"></div><div id=\"js-custom\"></div><script src=\"/admin/js/chunk-vendors.6bc95897.js\"></script><script src=\"/admin/js/app.67f73e35.js\"></script></body></html>": not an object`

this is the production response . @long2ice
