### ISSUE TITLE
facing issue in running docker 

### ISSUE THREAD

**Issue by pvssrikanth** [fastapi-admin/fastapi-admin#44]
Dear Sir,

 File "uvloop/loop.pyx", line 1994, in uvloop.loop.Loop.create_connection
app_1  | ConnectionRefusedError: [Errno 111] Connection refused
app_1  | 
app_1  | ERROR:    Application startup failed. Exiting.
app_1  | INFO:     Started server process [1]
app_1  | INFO:     Waiting for application startup.
app_1  | ERROR:    Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 526, in lifespan
app_1  |     async for item in self.lifespan_context(app):
app_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 467, in default_lifespan
app_1  |     await self.startup()
app_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 502, in startup
app_1  |     await handler()
app_1  |   File "./examples/main.py", line 34, in startup
app_1  |     redis = await aioredis.create_redis_pool("redis://localhost", encoding="utf8")
app_1  |   File "/usr/local/lib/python3.9/site-packages/aioredis/commands/__init__.py", line 188, in create_redis_pool
app_1  |     pool = await create_pool(address, db=db,
app_1  |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 58, in create_pool
app_1  |     await pool._fill_free(override_min=False)
app_1  |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 383, in _fill_free
app_1  |     conn = await self._create_new_connection(self._address)
app_1  |   File "/usr/local/lib/python3.9/site-packages/aioredis/connection.py", line 111, in create_connection
app_1  |     reader, writer = await asyncio.wait_for(open_connection(
app_1  |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
app_1  |     return await fut
app_1  |   File "/usr/local/lib/python3.9/site-packages/aioredis/stream.py", line 23, in open_connection
app_1  |     transport, _ = await get_event_loop().create_connection(
app_1  |   File "uvloop/loop.pyx", line 2017, in create_connection
app_1  |   File "uvloop/loop.pyx", line 1994, in uvloop.loop.Loop.create_connection
app_1  | ConnectionRefusedError: [Errno 111] Connection refused
app_1  | 
app_1  | ERROR:    Application startup failed. Exiting.
fastapi-admin_app_1 exited with code 0
(testpy3.9) iibadmin@iibadmin-uat-ubuntu:~/Python-3.9.1/fastapi-admin$ sudo docker-comp

**Comment by long2ice** [comment]
What's the version?

**Comment by pvssrikanth** [comment]
Dear Sir,
Its ubuntu18.04 bionic

kindly help please

**Comment by long2ice** [comment]
Sorry, I mean fastapi-admin version, but the error is can not connect to redis

**Comment by pvssrikanth** [comment]
Dear Sir,

I took latest https://pypi.org/project/fastapi-admin/

and tried running pip install fastapi-admin

Collecting pypika-tortoise<0.2.0,>=0.1.0
  Using cached pypika_tortoise-0.1.0-py3-none-any.whl (42 kB)
Collecting iso8601<0.2.0,>=0.1.13
  Using cached iso8601-0.1.14-py2.py3-none-any.whl (9.5 kB)
Collecting pytz<2021.0,>=2020.4
  Using cached pytz-2020.5-py2.py3-none-any.whl (510 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: starlette, typing-extensions, pydantic,
fastapi, wcwidth, prompt-toolkit, python-dotenv, six, pycparser, cffi,
bcrypt, PyMySQL, aiomysql, aiosqlite, python-rapidjson, h11, click,
uvicorn, MarkupSafe, jinja2, passlib, colorama, xlsxwriter,
pypika-tortoise, iso8601, pytz, tortoise-orm, pyjwt, fastapi-admin
ERROR: After October 2020 you may experience errors when installing or
updating packages. This is because pip will change the way that it resolves
dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with
the new resolver before it becomes the default.

tortoise-orm 0.17.2 requires aiosqlite<0.17.0,>=0.16.0, but you'll have
aiosqlite 0.17.0 which is incompatible.
Successfully installed MarkupSafe-1.1.1 PyMySQL-0.9.3 aiomysql-0.0.21
aiosqlite-0.17.0 bcrypt-3.2.0 cffi-1.14.5 click-7.1.2 colorama-0.4.4
fastapi-0.63.0 fastapi-admin-0.3.3 h11-0.12.0 iso8601-0.1.14 jinja2-2.11.3
passlib-1.7.4 prompt-toolkit-3.0.18 pycparser-2.20 pydantic-1.8.1
pyjwt-2.1.0 pypika-tortoise-0.1.0 python-dotenv-0.17.1 python-rapidjson-1.0
pytz-2020.5 six-1.15.0 starlette-0.13.6 tortoise-orm-0.17.2
typing-extensions-3.10.0.0 uvicorn-0.13.4 wcwidth-0.2.5 xlsxwriter-1.4.0
WARNING: You are using pip version 20.2.3; however, version 21.1.1 is
available.
You should consider upgrading via the
'/home/iibadmin/srik/mayprojects/fastadminenv/bin/python3.9 -m pip install
--upgrade pip' command.
(fastadminenv) ***@***.***:~/srik/mayprojects$

Please help in resolution

Thanks

**Comment by long2ice** [comment]
pypi is not latest, you can try install from source code

**Comment by pvssrikanth** [comment]
Dear Sir

Can you please give link of source tar zip file

And after installing the command to run fastapiadnin

Thanks a lot for your prompt replies

Regards
Srikanth

**Comment by long2ice** [comment]
use git clone

**Comment by pvssrikanth** [comment]
Ok sir
I did git clone only
So you mean instead of pip try install source

Ok I will do

How to run after installing

Please give command

**Comment by long2ice** [comment]
You can see documation there

**Comment by pvssrikanth** [comment]
Ok sure

Thanks

Will refer documentation

**Comment by pvssrikanth** [comment]
Dear Sir,
I referred documentation  built from  source

   File "uvloop/loop.pyx", line 1994, in uvloop.loop.Loop.create_connection
app_1  | ConnectionRefusedError: [Errno 111] Connection refused
app_1  |
app_1  | ERROR:    Application startup failed. Exiting.
app_1  | INFO:     Started server process [1]
app_1  | INFO:     Waiting for application startup.
app_1  | ERROR:    Traceback (most recent call last):
app_1  |   File
"/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 526, in
lifespan
app_1  |     async for item in self.lifespan_context(app):
app_1  |   File
"/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 467, in
default_lifespan
app_1  |     await self.startup()
app_1  |   File
"/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 502, in
startup
app_1  |     await handler()
app_1  |   File "./examples/main.py", line 34, in startup
app_1  |     redis = await aioredis.create_redis_pool("redis://localhost",
encoding="utf8")
app_1  |   File
"/usr/local/lib/python3.9/site-packages/aioredis/commands/__init__.py",
line 188, in create_redis_pool
app_1  |     pool = await create_pool(address, db=db,
app_1  |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py",
line 58, in create_pool
app_1  |     await pool._fill_free(override_min=False)
app_1  |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py",
line 383, in _fill_free
app_1  |     conn = await self._create_new_connection(self._address)
app_1  |   File
"/usr/local/lib/python3.9/site-packages/aioredis/connection.py", line 111,
in create_connection
app_1  |     reader, writer = await asyncio.wait_for(open_connection(
app_1  |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in
wait_for
app_1  |     return await fut
app_1  |   File
"/usr/local/lib/python3.9/site-packages/aioredis/stream.py", line 23, in
open_connection
app_






*1  |     transport, _ = await get_event_loop().create_connection(app_1  |
  File "uvloop/loop.pyx", line 2017, in create_connectionapp_1  |   File
"uvloop/loop.pyx", line 1994, in uvloop.loop.Loop.create_connectionapp_1  |
ConnectionRefusedError: [Errno 111] Connection refusedapp_1  | app_1  |
ERROR:    Application startup failed. Exiting.fastapi-admin_app_1 exited
with code 0(fastadminenv)
***@***.***:~/srik/mayprojects/fastadminenv/fastapi-admin$
~*

*kindly help  hwo  to resolve *

**Comment by long2ice** [comment]
Current is hard code redis connection in example, you should update it
