### ISSUE TITLE
Issue with resource resolving.

### ISSUE THREAD

**Issue by Addovej** [fastapi-admin/fastapi-admin#51]
Hi!

There are some unobvious thing with getting Tortose model in the fastapi_admin.depends:

```
def get_model(resource: Optional[str] = Path(...)):
    if not resource:
        return
    for app, models in Tortoise.apps.items():
        model = models.get(resource.title())
        if model:
            return model
```

In the models variable a keys in case sensitive. And get model with word capitalization. So if a model name will consist of two and more words (in CamelCase) then this resource will not found.

Example:
 models has keys 'Admin', 'BugReport'. But in resource arg will be 'bugreport'.

Maybe need add to the documentation this restriction description or fix get_model function?

As variant of solution I can suggest following:

```
def get_model(resource: Optional[str] = Path(...)):
    if not resource:
        return
    for app, models in Tortoise.apps.items():
        models = {key.lower(): val for key, val in models.items()}
        
        model = models.get(resource.title())
        if model:
            return model
```

**Comment by long2ice** [comment]
That's right, I fixed it

**Comment by Addovej** [comment]
Thank you
