### ISSUE TITLE
PK values only integer

### ISSUE THREAD

**Issue by Addovej** [fastapi-admin/fastapi-admin#52]
Hi! It's me again))

Could you please replace type annotation for pk path params in the admin routes with Union[int, UUID]?

It would allow to use UUID type for primary keys.

**Comment by long2ice** [comment]
That's ok

**Comment by Addovej** [comment]
Should I create PR or you will make it by yourself?

**Comment by long2ice** [comment]
I'm fixing it, thanks!

**Comment by long2ice** [comment]
I want make it `str` type, which suitable for `uuid` also?

**Comment by long2ice** [comment]
Fixed

**Comment by Addovej** [comment]
Thank you!
@long2ice 

There is an issue with "None path" requests. I'm not sure why is this happen, but for all admin requests (from browser) it makes one more request with None in the path. For example:

Loading `/admin/` -> in a browser console network tab appear one more request `/admin/None` request:
![image](https://user-images.githubusercontent.com/29037507/120790233-571a0f00-c53b-11eb-862b-d6534c7dca1f.png)

For case when getting update view, it send same request too: `/admin/{resource}/update/None` (None instead of PK). And in the update_view when getting an object we gets an error:

![image](https://user-images.githubusercontent.com/29037507/120790603-d7d90b00-c53b-11eb-824c-f0fe84cd7b41.png)

It because passed 'None' string value for PK field. And this not valid for int and uuid both.

Seems like Union[int, UUID] more works for this than str.

Also need research a common reason: why it makes one more request with 'None' value on each request. I'll try to find out this and let you know.

**Comment by Addovej** [comment]
I found the reason why it sends one more request on each:
I've not specified in the admin_app.configure() logo_url and favicon_url fields.

Specifying of these params is solving this error but it's not right behaviour when not specify because these params is not mandatory.

**Comment by long2ice** [comment]
You are right
