### ISSUE TITLE
静态文件重复加载问题

### ISSUE THREAD

**Issue by pppppppan** [fastapi-admin/fastapi-admin#56]
每次切换标签似乎所有的js  css文件都要请求一遍
这个方便优化吗
还有一个是国内用户建议使用unpkg的国内镜像
unpkg.zhimg.com

我看issues还是有挺多国人的

**Comment by long2ice** [comment]
后端渲染没办法避免，静态资源会有缓存不会多次请求

**Comment by long2ice** [comment]
另外，cdn可以通过覆盖base.html模板来解决
