### ISSUE TITLE
本地启动examble报错：/bin/sh -c mkdir -p /fastapi-admin

### ISSUE THREAD

**Issue by xflcx1991** [fastapi-admin/fastapi-admin#59]
`ERROR: Service 'app' failed to build: The command '/bin/sh -c mkdir -p /fastapi-admin' returned a non-zero code: 1` 抛开权限不说，这里既然用了`-c`是不是应该把后面的mkdir及其参数用引号包裹起来？
`/bin/sh -c 'mkdir -p /fastapi-admin'`
我该如何修改启动脚本？

权限问题，我手动创建了`/fastapi-admin`，并把文件夹属主改为了当前用户

**Comment by xflcx1991** [comment]
嘿，报错的是树莓派，在Ubuntu16.04上是好的。看来是平台的差异问题，Ubuntu16.04启动后docker容器使用restarting状态，我再去查查。

**Comment by long2ice** [comment]
树莓派要改一下python的基础镜像吧，只能使用arm的

**Comment by xflcx1991** [comment]
> 树莓派要改一下python的基础镜像吧，只能使用arm的

请问你在那个平台开发的，我不想折腾环境了，搞个虚拟机弄成和你一样的系统环境。

**Comment by long2ice** [comment]
按理说跟环境没关系，Linux Mac都可以

**Comment by xflcx1991** [comment]
> 按理说跟环境没关系，Linux Mac都可以

谢谢，我手动运行`env 一些环境变量 uvicorn examples.main:app_ --port 8000`跑起来了。此问题终结，不折腾环境了，赶紧看代码去。
