### ISSUE TITLE
How to create new page without tortoise model

### ISSUE THREAD

**Issue by royalwood** [fastapi-admin/fastapi-admin#65]
Hello.
I want to add new page to admin panel which shows data from MongoDB.
I know that this library doesn't support NoSQL database.
But I need to do this and want to add such functionality on my project.
So I want to know how can I create new page without model. and then I think I can put some buttons or use dropdown from default template to call api which returns data of mongodb.
so that I can show data on new page.
Looking forward to get some help with this!

**Comment by long2ice** [comment]
You can write custom page

**Comment by royalwood** [comment]
How can I create new custom page?
I tried to add this to create new page, 
Menu(
                    name="Mongodb",
                    children=[
                        Menu(name="CollectionName", url="/rest/CollectionName", icon="fa fa-list"),
                    ]
                ),

But it causes error since CollectionName is not tortoise registered model.
Could you please let me know how I can create new custom page without model related?

**Comment by long2ice** [comment]
See https://fastapi-admin.github.io/custom/page/
