### ISSUE TITLE
HTTP error 404 while being unauthorized

### ISSUE THREAD

**Issue by radiophysicist** [fastapi-admin/fastapi-admin#72]
Hello,

It is a bit confusing in example app to obtain 404 instead of 401 while not being authorized.
Wouldn't it be more correct to return 401 error here:
https://github.com/fastapi-admin/fastapi-admin/blob/master/fastapi_admin/depends.py#L73-L73
?

**Comment by long2ice** [comment]
Yes

**Comment by long2ice** [comment]
Change that

**Comment by radiophysicist** [comment]
Here is PR:
https://github.com/fastapi-admin/fastapi-admin/pull/74

**Comment by radiophysicist** [comment]
:)

**Comment by long2ice** [comment]
Thanks but fixed that already
